;;; org-version.el --- autogenerated file, do not edit
;;
;;; Code:
;;;###autoload
(defun org-release ()
  "The release version of org-mode.
  Inserted by installing org-mode or when a release is made."
   (let ((org-release "8.0.6"))
     org-release))
;;;###autoload
(defun org-git-version ()
  "The Git version of org-mode.
  Inserted by installing org-mode or when a release is made."
   (let ((org-git-version "release_8.0.6-332-g4899c7"))
     org-git-version))
;;;###autoload
(defvar org-odt-data-dir "/Users/zpinter/.emacs.d/org-mode/data"
  "The location of ODT styles.")

(provide 'org-version)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; coding: utf-8
;; End:
;;; org-version.el ends here
