;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        coffee-dedent-line-backspace
        cua--prefix-repeat-handler
        cua--shift-control-c-prefix
        cua-delete-region
        cua-resize-rectangle-left
        cua-resize-rectangle-right
        mc/add-cursor-on-click
        org-beginning-of-line
        org-self-insert-command
        sp--cua-replace-region
        ))

(setq mc/cmds-to-run-once
      '(
        exit-recursive-edit
        sp--self-insert-command
        ))
