;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		  cua--prefix-repeat-handler
		  cua--shift-control-c-prefix
		  cua-resize-rectangle-left
		  cua-resize-rectangle-right
		  mc/add-cursor-on-click
		  ))

(setq mc/cmds-to-run-once
      '(
		  exit-recursive-edit
		  ))
