; -*- mode: emacs-lisp; -*-
; (source gnu)
(source melpa)
(source org)

(depends-on "ido-vertical-mode")
(depends-on "ido-ubiquitous")
(depends-on "smex")
(depends-on "org")
(depends-on "elscreen")
(depends-on "solarized-theme")
(depends-on "powerline")

;; (depends-on "ibuffer")
(depends-on "nxml")
(depends-on "auto-complete")
(depends-on "ac-dabbrev")
(depends-on "move-text")
(depends-on "ert") ;;related to auto-complete
(depends-on "fuzzy") ;;related to auto-complete
(depends-on "popup") ;;related to auto-complete
(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "go-mode")
(depends-on "go-autocomplete")
(depends-on "magit")
(depends-on "mo-git-blame")
(depends-on "git-commit-mode")
(depends-on "git-gutter")
(depends-on "gitconfig-mode")
(depends-on "gitignore-mode")
(depends-on "git-rebase-mode")
(depends-on "puppet-mode")
(depends-on "markdown-mode")
(depends-on "lua-mode")
(depends-on "window-numbering")
(depends-on "haml-mode")
(depends-on "nav")
(depends-on "json-mode")
(depends-on "csharp-mode")
(depends-on "undo-tree")
(depends-on "csv-nav")
(depends-on "sass-mode")
(depends-on "scss-mode")
(depends-on "whitespace-cleanup-mode")
(depends-on "less-css-mode")
(depends-on "erlang")
(depends-on "rainbow-delimiters")
(depends-on "handlebars-sgml-mode")
(depends-on "expand-region")
(depends-on "multiple-cursors")
(depends-on "wrap-region")
(depends-on "popwin")
(depends-on "smart-tab")
(depends-on "thrift")
(depends-on "coffee-mode")
(depends-on "yaml-mode")
(depends-on "editorconfig")
(depends-on "hexrgb")
(depends-on "projectile")
(depends-on "helm")
(depends-on "helm-projectile")
(depends-on "helm-ag")
(depends-on "smartparens")
(depends-on "jedi") ;;python
(depends-on "smex")

;; (depends-on "cask")
;; (depends-on "dash")
;; (depends-on "drag-stuff")
;; (depends-on "expand-region")
;; (depends-on "magit")
;; (depends-on "multiple-cursors")
;; (depends-on "popwin")
;; (depends-on "projectile")
;; (depends-on "s")
;; (depends-on "smex")
;; (depends-on "wrap-region")
;; (depends-on "yasnippet")
