; -*- mode: emacs-lisp; -*-
(load "~/.emacs.d/zconfig.el")

(zconfig-start-benchmark)

(zconfig-load "core")
(zconfig-load "customize")
(zconfig-load "org-mode")
(zconfig-load "org-jira")
(zconfig-load "apel")
(if (not (iswindows)) (zconfig-load "elscreen")) ;breaks emacs-w32 on cygwin
(zconfig-load "easypg")
(zconfig-load "window-settings")
(zconfig-load "solarized-theme")
;; (zconfig-load "color-theme")
;; (zconfig-load "color-theme-zenburn")
(zconfig-load "ibuffer")
(zconfig-load "hippie-expand")
(zconfig-load "nxml")
;; (zconfig-load "ruby")
(zconfig-load "ruby-minimal")
(zconfig-load "auto-complete")
(zconfig-load "python-mode")
;; (zconfig-load "pymacs")
(zconfig-load "mirah")
(zconfig-load "js2-mode")
(zconfig-load "android-mode")
;; (zconfig-load "yasnippet")
(zconfig-load "git-contrib")
(zconfig-load "egit")
(zconfig-load "magit")
(zconfig-load "mo-git-blame")
(zconfig-load "git-minimal")
(zconfig-load "twitter")
(zconfig-load "post-mode")
;; (zconfig-load "gnus")
(zconfig-load "bbdb")
(zconfig-load "puppet-mode")
(zconfig-load "markdown-mode")
;; (zconfig-load "ess")
(zconfig-load "lua-mode")
(zconfig-load "xml-rpc") ;needed by trac-wiki and jira
;; (zconfig-load "trac-wiki")
(zconfig-load "confluence-el")
;; (zconfig-load "jira")
(zconfig-load "remember")
(zconfig-load "deft")
;; (zconfig-load "paredit")
(zconfig-load "window-numbering")
;; (zconfig-load "slime")
;; (zconfig-load "clojure-mode")
(zconfig-load "cheat")
(zconfig-load "shell-current-directory")
(zconfig-load "erc")
(zconfig-load "haml-mode")
(zconfig-load "smali")
(zconfig-load "helm")
(zconfig-load "helm-git")
;; (zconfig-load "anything")
(if (not (iswindows)) (zconfig-load "w3m")) ;not important enough to solve on windows
(zconfig-load "flyspell")
(zconfig-load "rinari")
;; (zconfig-load "flex")
(zconfig-load "nav")
(zconfig-load "open-resource")
(zconfig-load "breadcrumb")
(zconfig-load "xcscope")
;; (zconfig-load "json") ;;required by json-pretty-print
;; (zconfig-load "json-pretty-print")
;; (zconfig-load "company-mode")
;; (zconfig-load "cedet")
;; (zconfig-load "ecb")
;; (zconfig-load "jdee")
;; (zconfig-load "textmate")
(zconfig-load "csharp")
(zconfig-load "undo-tree")
(zconfig-load "jabber")
(zconfig-load "ack")
(zconfig-load "csv-mode")
(zconfig-load "scss-mode")
(zconfig-load "ace-jump-mode")
(zconfig-load "erlang-mode")
(zconfig-load "rvm")
;; (zconfig-load "emacs-eclim")
(zconfig-load "expand-region") ;;should come after undo-tree
(zconfig-load "multiple-cursors")
(zconfig-load "etags")
(zconfig-load "smart-tab")
(zconfig-load "ws-trim")
(zconfig-load "tweaks")
(zconfig-load "mu4e")
;; (zconfig-load "emacs-git-gutter")
(zconfig-load "ido")
;;(zconfig-load "el-get-setup")
(zconfig-load "smex")
;; (zconfig-load "server")
;; (zconfig-load "edit-server")

(zconfig-finish-benchmark)

(put 'narrow-to-region 'disabled nil)
(put 'set-goal-column 'disabled nil)
(put 'downcase-region 'disabled nil)
